-- Sporcu antrenman kayitlari icin tablo/policy kurulumu.
-- Supabase > SQL Editor icinde bir kez calistirin.

create table if not exists public.antrenmanlar (
  id bigint generated by default as identity primary key,
  sporcu_id uuid not null references public.profiles(id) on delete cascade,
  tarih timestamptz not null default now(),
  hareket text not null,
  sure_saniye integer not null default 0,
  toplam integer not null default 0,
  dogru integer not null default 0,
  hatali integer not null default 0,
  basari_yuzdesi numeric(5,2) not null default 0,
  en_sik_form_hatasi text
);

alter table public.antrenmanlar
  add column if not exists en_sik_form_hatasi text;

alter table public.antrenmanlar enable row level security;

drop policy if exists "sporcu antrenmanlarini gorur" on public.antrenmanlar;
create policy "sporcu antrenmanlarini gorur" on public.antrenmanlar
for select using (
  sporcu_id = auth.uid()
  or public.baglanti_bana_ait_mi(sporcu_id)
);

drop policy if exists "sporcu antrenman ekler" on public.antrenmanlar;
create policy "sporcu antrenman ekler" on public.antrenmanlar
for insert with check (
  sporcu_id = auth.uid()
);

drop policy if exists "sporcu antrenman gunceller" on public.antrenmanlar;
create policy "sporcu antrenman gunceller" on public.antrenmanlar
for update using (
  sporcu_id = auth.uid()
) with check (
  sporcu_id = auth.uid()
);

create index if not exists antrenmanlar_sporcu_tarih_idx
on public.antrenmanlar (sporcu_id, tarih desc);
