-- Ödev numarası, ödev tarih aralığı ve hoca geri bildirimleri.
-- Supabase > SQL Editor ekranında bir kez çalıştırın.

alter table public.programlar
  add column if not exists odev_no integer not null default 1,
  add column if not exists baslangic_tarihi date,
  add column if not exists bitis_tarihi date;

update public.programlar
set baslangic_tarihi = coalesce(baslangic_tarihi, tarih),
    bitis_tarihi = coalesce(bitis_tarihi, tarih)
where baslangic_tarihi is null or bitis_tarihi is null;

alter table public.programlar
  drop constraint if exists programlar_tarih_araligi_check;
alter table public.programlar
  add constraint programlar_tarih_araligi_check
  check (bitis_tarihi is null or baslangic_tarihi is null or bitis_tarihi >= baslangic_tarihi);

create index if not exists programlar_odev_idx
on public.programlar (sporcu_id, odev_no, baslangic_tarihi, bitis_tarihi);

create table if not exists public.bildirimler (
  id bigint generated by default as identity primary key,
  hoca_id uuid not null,
  sporcu_id uuid not null,
  odev_no integer not null,
  mesaj text not null check (char_length(trim(mesaj)) between 1 and 1000),
  okundu boolean not null default false,
  created_at timestamptz not null default now(),
  constraint bildirimler_hoca_id_fkey
    foreign key (hoca_id) references public.profiles(id) on delete cascade,
  constraint bildirimler_sporcu_id_fkey
    foreign key (sporcu_id) references public.profiles(id) on delete cascade
);

create index if not exists bildirimler_sporcu_tarih_idx
on public.bildirimler (sporcu_id, created_at desc);

alter table public.bildirimler enable row level security;

drop policy if exists "sporcu bildirimlerini görür" on public.bildirimler;
create policy "sporcu bildirimlerini görür" on public.bildirimler
for select using (sporcu_id = auth.uid());

drop policy if exists "sporcu bildirimi okur" on public.bildirimler;
create policy "sporcu bildirimi okur" on public.bildirimler
for update using (sporcu_id = auth.uid())
with check (sporcu_id = auth.uid());

drop policy if exists "hoca bildirim gönderir" on public.bildirimler;
create policy "hoca bildirim gönderir" on public.bildirimler
for insert with check (
  hoca_id = auth.uid()
  and public.hoca_miyim()
  and public.sporcu_bana_bagli_mi(sporcu_id)
);

drop policy if exists "hoca gönderdiğini görür" on public.bildirimler;
create policy "hoca gönderdiğini görür" on public.bildirimler
for select using (
  hoca_id = auth.uid()
  and public.sporcu_bana_bagli_mi(sporcu_id)
);
