create table if not exists public.programlar (
  id bigint generated by default as identity primary key,
  hoca_id uuid not null references public.profiles(id) on delete cascade,
  sporcu_id uuid not null references public.profiles(id) on delete cascade,
  tarih date not null,
  hareket text not null check (
    hareket in ('Squat', 'Şınav', 'Barfiks', 'Aç-Kapa Zıplama', 'Gövde Çevirme')
  ),
  hedef_tekrar integer not null check (hedef_tekrar between 1 and 500),
  notlar text not null default '',
  durum text not null default 'planlandi'
    check (durum in ('planlandi', 'tamamlandi')),
  created_at timestamptz not null default now()
);

create index if not exists programlar_sporcu_tarih_idx
on public.programlar (sporcu_id, tarih);

alter table public.programlar enable row level security;

drop policy if exists "programı taraflar görür" on public.programlar;
create policy "programı taraflar görür" on public.programlar
for select using (
  sporcu_id = auth.uid()
  or (hoca_id = auth.uid() and public.sporcu_bana_bagli_mi(sporcu_id))
);

drop policy if exists "hoca program ekler" on public.programlar;
create policy "hoca program ekler" on public.programlar
for insert with check (
  hoca_id = auth.uid()
  and public.hoca_miyim()
  and public.sporcu_bana_bagli_mi(sporcu_id)
);

drop policy if exists "program güncellenir" on public.programlar;
create policy "program güncellenir" on public.programlar
for update using (
  sporcu_id = auth.uid()
  or (hoca_id = auth.uid() and public.sporcu_bana_bagli_mi(sporcu_id))
)
with check (
  sporcu_id = auth.uid()
  or (hoca_id = auth.uid() and public.sporcu_bana_bagli_mi(sporcu_id))
);

drop policy if exists "hoca program siler" on public.programlar;
create policy "hoca program siler" on public.programlar
for delete using (
  hoca_id = auth.uid() and public.sporcu_bana_bagli_mi(sporcu_id)
);

drop policy if exists "sporcu program siler" on public.programlar;
create policy "sporcu program siler" on public.programlar
for delete using (
  sporcu_id = auth.uid()
);
